### ISSUE TITLE
Nuget Package structure prevents cont. integration builds and places dll in root proj folder

### ISSUE THREAD

**Issue by mulgurul** [Corey-M/NAudio.Lame#25]
I'm working devops on a project which has several projects including the NAudion.Lame nuget package.

It is causing some problems that the Nuget package throws the libmp3lame.dlls into the root og the VS project using the Nuget package.

As one normally not wants to check in Nuget dependencies, then all dll's are ignored on commit.
All dll's are then restored into build output on build server using nuget package manager.

This is causing some problems with the ddl breaking this standard.

Is it possible to suggest that the libmp3lame.xx.dll are handles same way as the wrapper dll's, so they are restored into build output as part of standard Nuget restore on build.

Thanks a lot

Best regards, Peter Meldgaard, Denmark

**Comment by Corey-M** [comment]
I finally got around to figuring this out.  After a bit of messing about, v1.0.8 now uses a `.targets` file to copy the native DLLs into the build folder instead of adding the files to the project.  Seems that the powershell script to update the project's properties would only work when working on the solution in VS, and would fail everywhere else.
