### ISSUE TITLE
Unable to convert wav audio to mp3

### ISSUE THREAD

**Issue by Shifaat** [Corey-M/NAudio.Lame#3]
Hi. I am looking for a way to convert a wav file into mp3 in MVC project. I used the method 'WaveToMP3' from the example code you've mentioned. It does create an mp3 file, But when I play it, there is just static noise. No original audio.

Am I doing something wrong here?

**Comment by Corey-M** [comment]
On the off-chance that you haven't given up in disgust, try using `AudioFileReader` instead of `WavFileReader` to read the file.  It converts to 32-bit floating point samples that the LAME encoder prefers.  Also, try the latest code from the Experimental branch... not much changed in the actual encoding, but the wrapper code has been reorganized a little.

**Comment by Corey-M** [comment]
Closing as this is a very old issue.  Questions like this can be best directed to Stack Overflow with the `NAudio` tag.
