### ISSUE TITLE
1.1.0-pre1 | .NET Core | Could not load file or assembly 'WrapLame'

### ISSUE THREAD

**Issue by AndyPresto** [Corey-M/NAudio.Lame#32]
Using the new 1.1.0-pre1 release found on Nuget with a .NET Core 2.2 app.

I've built a minimalist example console app to try and convert a .wav file to a .mp3 file Here's my code.

    class Program
    {
        static void Main(string[] args)
        {
            var directory = AppContext.BaseDirectory;
            var inputFile = Path.Combine(directory, "test.wav");
            var outputFileName = Path.Combine(directory, "test.mp3");

            WaveToMP3(inputFile, outputFileName);
        }

        // Convert WAV to MP3 using libmp3lame library
        public static void WaveToMP3(string waveFileName, string mp3FileName, int bitRate = 128)
        {
            using (var reader = new AudioFileReader(waveFileName))
            using (var writer = new LameMP3FileWriter(mp3FileName, reader.WaveFormat, bitRate))
                reader.CopyTo(writer);
        }
    }

The code works on .Net Framework, however on Core we receive the below error.

'Could not load file or assembly 'WrapLame, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'

![image](https://user-images.githubusercontent.com/8163146/61771286-a2304a80-ae19-11e9-986f-421f34855e45.png)

**Comment by sabiland** [comment]
Yep I have the same problem on latest Net Core.

**Comment by Michael-Artlist** [comment]
Same Issue

**Comment by mattiabaldinger** [comment]
+1

**Comment by jtorvald** [comment]
+1

**Comment by Corey-M** [comment]
This is probably the same as #33 and relates to changes in the way static constructors are called in .NET Core.  In .NET Framework the order in which things are called is a little hinky.  .NET Core does it in a different way, and that messes up the library.

Not sure where WrapLame (the old name for LameDLLWrap) got involved.

@AndyPresto @sabiland @Michael-Artlist @mattiabaldinger

**Comment by Corey-M** [comment]
@jtorvald Please don't try to use this with Xamarin.  `libmp3lame.dll` is Windows-specific and will not work on any other operating system.  I develop on Windows exclusively, so I haven't ever tried to make this work anywhere else.

**Comment by jtorvald** [comment]
@Corey-M thanks for the reply. Would that be possible you think? Shouldn't that just work because it's .NET standard?

**Comment by Corey-M** [comment]
@jtorvald the problem is that while the managed code is .NET Standard, it is a wrapper around a Windows Native library.  The native library exists on other platforms, so other platforms could potentially be supported by NAudio.Lame... but since I only develop on Windows it is unlikely I'll ever manage to do this.

I'm always open to forks and pull requests of course.  I created this for my own use and have learned quite a lot by releasing it this way, but it's very much of an infrequent hobby of mine.  I hardly ever touch audio stuff these days.

So if anyone would like to get involved and improve the code I'd be happy to accept their input :)

For Xamarin though... I don't know if you'll find any LAME native binaries for iOS or Android.  LAME is kind of old now.  FFMPEG would be a better library for cross-platform.  It doesn't really fit what I'm doing here though.

**Comment by jtorvald** [comment]
@Corey-M Thanks. I will look a bit around for alternatives 👍

**Comment by Corey-M** [comment]
@AndyPresto Can you please check out the new pre-release on NuGet (v1.1.0-pre3) and let me know if it fixes your problem?  I'm going to close this off shortly.

**Comment by AndyPresto** [comment]
@Corey-M v1.1.0-pre3 has fixed the issue. 

I just tested in .net core 3.1 and it worked fine. Thank you.
