### ISSUE TITLE
is .NET Framework any more not supporting?

### ISSUE THREAD

**Issue by atrezonator** [Corey-M/NAudio.Lame#40]
is .NET Framework 4.0 any more not supporting? if not, that how use it 1,1,1 ver ?

![image](https://user-images.githubusercontent.com/34670899/79055097-de7b3380-7c52-11ea-89eb-39193dcb3146.png)
![image](https://user-images.githubusercontent.com/34670899/79055104-e9ce5f00-7c52-11ea-8c3d-c20d1477cee4.png)

**Comment by Corey-M** [comment]
This can happen if you upgrade `NAudio.Lame` without also upgrading `NAudio` to v1.10 or higher.  This should happen automatically but it seems not to be doing so in some cases.  Open the NuGet package manager for your project and manually upgrade `NAudio` to the latest version.

I'll be updating the nuget package for `NAudio.Lame` shortly.  That may also fix the issue.

**Comment by atrezonator** [comment]
In 1.1.2 same

**Comment by Corey-M** [comment]
@atrezonator Sorry, I obviously wasn't thinking about this very well at the time.  Since v1.1.0 NAudio.Lame is compiled as a .NET Standard 2.0 library which requires at least .NET Framework v4.6.1.  The last version that supported .NET Framework v4.0 was NAudio.Lame v1.0.9, which is still available on NuGet.

Since earlier earlier versions of .NET v4.x are out of support at this point I don't think that there's much to be gained from retrofitting the library for an older, unsupported .NET version. I've got a pull request to support .NET 4.5 that I'm also considering rejecting for the same reasons.

If you need the latest updates and can't upgrade your project to .NET FW v4.6.1 or higher then you could fork the library from before I did the .NET Standard overhaul ([Commit b496c27fa8...][1]) or check out the [.NET 4.0 retrofit][2] branch I've just pushed up.  It passes the existing tests on .NET 4.5.0 so it might work for you.

[1]: https://github.com/Corey-M/NAudio.Lame/tree/b496c27fa875eeec151d75bbb1c30ce24d49c17c
[2]: https://github.com/Corey-M/NAudio.Lame/tree/net4_v1.1.1_retrofit
