### ISSUE TITLE
Conversion producing sped up audio as of v1.1.1

### ISSUE THREAD

**Issue by bmmiller** [Corey-M/NAudio.Lame#43]
We've been humming a long fine for quite a while but the upgrade to v1.1.1 has caused our WAV files, once converted to MP3, to be sped up in an unintelligible manner.  Downgrading to v1.1.0 and we're good again.

Any idea what could be causing this?  I imagine most people have been fine but we've tried a handful of different overloads of LameMP3FileWriter with different bitrate/presets and all are producing the same broken output.

**Comment by AlasdairKing** [comment]
I found exactly the same. I downgraded to 1.1.0, worked fine then.

**Comment by ftamminga** [comment]
Here the same. I had to downgrade to get it right again. The file is sped up by a factor ~5.5.

**Comment by Corey-M** [comment]
OK, it  turns out I messed up when I put the new configuration class in.  As a result it wasn't setting the sample rate or number of channels.  If you're working with 8khz mono files they will be encoded as 44.1khz stereo, for about 11x speed and  probably unintelligible.

I've fixed this in 1.1.2, available shortly.
