### ISSUE TITLE
Call LameMP3FileWriter.Write() from Task.Run()

### ISSUE THREAD

**Issue by VicLo2020** [Corey-M/NAudio.Lame#60]
Hello
How can I solve this problem?
SendData() is called from the program.
stream - network

I have code:
_mp3Writer = new LameMP3FileWriter(stream,...);
...
        private ConcurrentQueue<short[]> queue = new ConcurrentQueue<short[]>();
        public async void SendData(short[] data)
        {
            if (_mp3Writer == null || !IsConnected) return;
            queue.Enqueue(data);
            // WriteAsync not handled by LameMP3FileWriter :(
            await Task.Run(() => SendDataFromQueue());
        }
        private void SendDataFromQueue()
        {
            if (queue.TryDequeue(out short[] data))
            {
                byte[] bytes = new byte[data.Length * sizeof(short)];
                Buffer.BlockCopy(data, 0, bytes, 0, bytes.Length);
                 _mp3Writer.Write(bytes, 0, bytes.Length);
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
            }
        }

I get exception:
Managed Debugging Helper 'CallbackOnCollectedDelegate' : "A delegate of type 'LameDLLWrap!LameDLLWrap.delReportFunction::Invoke' received by the garbage collector was called back. This can cause application crashes and data corruption or loss. Passing delegates to unmanaged code, managed application must keep them alive until it is guaranteed that they will never be called again."

Thank you

**Comment by Corey-M** [comment]
Are you setting any callbacks on the LameMP3FileWriter?

**Comment by VicLo2020** [comment]
> Are you setting any callbacks on the LameMP3FileWriter?

No. The program uses only the function of writing to the stream.

**Comment by Corey-M** [comment]
OK, now I think I have a handle on it.

First, LAME is not thread-safe. This normally isn't an issue, but there are some parts of the state that can become corrupt if you have multiple threads operating on the one context simultaneously. I wrote the `LameMP3FileWriter` on the assumption that, since it has no `*Async` methods, it would be understood that it wasn't intended for multi-threaded shenannigans. (I always assume that if an object doesn't declare itself to be at least thread-aware then it's not thread-safe.)

That said, the error you're getting seems to indicate that the `LameMP3FileWriter` is being disposed before all of your `SendDataFromQueue` tasks are completed processing. You'll need to examine your code to determine whether this is possible, and it's probably a good idea to ensure that the writer isn't going to be disposed while any writes are pending. At least acquire a lock around the write and dispose operations to ensure that the LAME context isn't corrupted or disposed while in use.

    // WriteAsync not handled by LameMP3FileWriter :(

Yes, that's by design. I know asynchronous programming is popular, but not everything fits in that paradigm.

If you absolutely must have asynchronous operation then I suggest you write a wrapper class that either locks around all access to the underlying `LameMP3FileWriter` or implements a full thread of its' own. I'd move the queueing and write loop in there as a minimum.

**Comment by VicLo2020** [comment]
At this stage, I have created a separate thread in which data is received from the ConcurrentQueue and passed to the LameMP3FileWriter.
This works for me.
