### ISSUE TITLE
Converting WAV to MP3 truncate file length

### ISSUE THREAD

**Issue by DirkFEng** [Corey-M/NAudio.Lame#67]
Hi team,

I have a short example for the "problem". I create two console apps (either with .NET Framework 4.72 and the other with .NET Core 6.0).
With Nuget I add NAudio 2.1.0 and NAudio.Lama 2.1.0.
When Convert in .NET Framework the result is ok. With .NET Core the file size was (in my case) only 1/4 of the original size.
Added my example file 16 seconds long is shrinked to 4s in .NET Core version.
Seems its only the case for Mono Audio files.

[AudioFile.zip](https://github.com/Corey-M/NAudio.Lame/files/11330561/AudioFile.zip)

using (var reader = new AudioFileReader("C:\Temp\AudioFile.wav"))
{
using (var fileWriter = new FileStream("C:\Temp\Convert.mp3", FileMode.Create, FileAccess.Write))
{
LameConfig lc = new LameConfig();
lc.Out
putSampleRate = 8000;
lc.BitRate = 16;
using (var wtr = new LameMP3FileWriter(fileWriter, reader.WaveFormat, lc))
{
reader.CopyTo(wtr);
wtr.Flush();
}
}
}

Thanks in advance.
Regards
Dirk F.

**Comment by Corey-M** [comment]
Something odd going on with the input. The `AudioFileReader` reads 12,800 bytes (in 32-bit IEEE Float format after decoding your ALAW) which is about 4 seconds worth, and won't read any further. I'm not sure why that's the case, but it seems like @markheath has introduced a bug somewhere.

I had a browse through the NAudio source (been a while) and I think the issue is in `BlockAlignReductionStream` which doesn't appear to like it when you try to read more bytes than the internal `CircularBuffer` can hold. I'll have to dive a little deeper into it to find where the error is, but in the meantime you can get around the issue by copying smaller chunks of samples at a time instead of using `CopyTo`.

By default `BlockAlignReductionStream` allocates enough space for (as you probably guessed) 4 seconds worth of samples. If you allocate a buffer for 2 seconds, or even 1 sample width less than 4 seconds, then subsequent reads will continue to work and you can copy the whole file:

```
var buffer = new byte[reader.WaveFormat.AverageSamplesPerSecond * 4 - reader.WaveFormat.BlockAlign].AsSpan();
using (var writer = new LameMP3FileWriter(fileWriter, reader.WaveFormat, lc))
{
    while (reader.Position < reader.Length)
    {
        int rc = reader.Read(buffer);
        if (rc < 1)
            break;
        writer.Write(buffer[..rc]);
}
```

It's not necessarily ideal, but it'll get the job done. At least it did in my testing with that file.
