### ISSUE TITLE
Type `NAudio.Wave.WaveFileReader' does not contain a definition for `CopyTo'

### ISSUE THREAD

**Issue by tim-hub** [Corey-M/NAudio.Lame#9]
## Error Log:
> error CS1061: Type `NAudio.Wave.WaveFileReader' does not contain a definition for `CopyTo' and no extension method `CopyTo' of type `NAudio.Wave.WaveFileReader' could be found (are you missing a using directive or an assembly reference?)

## What the codes are just the same as the example
```
	// Convert WAV to MP3 using libmp3lame library
	static void WaveToMP3(string waveFileName, string mp3FileName, int bitRate = 32)
	{
		var reader = new WaveFileReader(waveFileName);
		var writer = new LameMP3FileWriter(mp3FileName, reader.WaveFormat, bitRate);


		reader.CopyTo(writer);
		
	}
```

It is a really annoying problem, and I have no idea about how to fix it. Hope your help.

**Comment by Corey-M** [comment]
`NAudio.Wave.WaveFileReader` subclasses `NAudio.Wave.WaveStream` which in turn subclasses `System.IO.Stream`... which implements the `CopyTo` method.  If you aren't able to use `CopyTo` then something is drastically wrong.

`System.IO.Stream` has been defined in `mscorlib` since at least .NET 1.1, and you shouldn't be able to build a program without it.  That eliminates 'missing assembly reference' from our list of causes.

Can you confirm that the `NAudio` nuget package is loaded and referenced in your application?  I vaguely recall having an issue with that before.  The dependency list on `NAudio.Lame` is supposed to ensure that the `NAudio` package is included, but it is possible to remove it after the fact and mess up your packages.

**Comment by tim-hub** [comment]
Thanks for your help. It worked.
